var ApiBaseUrl = Number(process.env.REACT_APP_PRODUCTION) === 1 ? process.env.REACT_APP_LIVE_BASE_URL : process.env.REACT_APP_LOCAL_BASE_URL;

export const API_Path = {
    login: ApiBaseUrl + "/api/admin/login",

    createnews: ApiBaseUrl + "/api/admin/createnews",
    getQueuedPost: ApiBaseUrl + "/api/admin/getScheduledPost",
    getDraftedPost: ApiBaseUrl + "/api/admin/getDraftedPost",
    getnews: ApiBaseUrl + "/api/getnews",
    gettrendingnews: ApiBaseUrl + "/api/gettrandingnews",
    getnewsdetails: ApiBaseUrl + "/api/admin/news",
    getinterest: ApiBaseUrl + "/api/admin/getinterestsList",
    addinterest: ApiBaseUrl + "/api/addinterest",
    removeinterest: ApiBaseUrl + "/api/removeinterest",

    showNewsComment: ApiBaseUrl + "/api/showcomment",

    addliveimg: ApiBaseUrl + "/api/addNewsImageOrVideo",

    faq: ApiBaseUrl + "/api/admin/faq",
    getfaq: ApiBaseUrl + "/api/faq",
    editfaq: ApiBaseUrl + "/api/admin/editfaq",
    specificfaq: ApiBaseUrl + "/api/faq/faqById",
    deletefaq: ApiBaseUrl + "/api/admin/removefaq",

    getprofile: ApiBaseUrl + "/api/profile",
    updateProfile: ApiBaseUrl + "/api/updateprofile",
    addemployee: ApiBaseUrl + "/api/addEmployee",
    getuser: ApiBaseUrl + "/api/admin/userlist",
    getuserdetails: ApiBaseUrl + "/api/admin/userdetails",
    manageUserStatus: ApiBaseUrl + "/api/admin/manageUserStatus",
    deleteUser: ApiBaseUrl + "/api/admin/deleteuser",
    getRecentPayerRequest: ApiBaseUrl + "/api/admin/getPrayerRequest",
    getAdminUsers: ApiBaseUrl + "/api/admin/employeeList",
    rejectPrayerRequest: ApiBaseUrl + "/api/admin/rejectPrayerRequest",
    approvePrayerRequest: ApiBaseUrl + "/api/admin/approvePrayerRequest",
    enabledDisabledEmployee: ApiBaseUrl + "/api/admin/changeEmpStatus",
    shareToNewsFeed: ApiBaseUrl + "/api/admin/shareToNewsFeed",
    getSharedPrayers: ApiBaseUrl + "/api/admin/getSharedPrayers",
    getApprovedPrayers: ApiBaseUrl + "/api/admin/getApprovedPrayerList",
    getRejectedPrayers: ApiBaseUrl + "/api/admin/getRejectedPrayerList",
    addEmployeeData: ApiBaseUrl + "/api/admin/employee",
    getRecentContents: ApiBaseUrl + "/api/admin/contentSuggestion",
    getSharedContentSuggestion: ApiBaseUrl + "/api/admin/sharedContentSuggestion",
    getDoneList: ApiBaseUrl + "/api/admin/contentSugMarks",
    shareContentSuggestion: ApiBaseUrl + "/api/admin/shareContentSuggestion",
    getMarkAsDone: ApiBaseUrl + "/api/admin/contentSugMark",
    getRecentTips: ApiBaseUrl + "/api/admin/tips",
    getSharedTips: ApiBaseUrl + "/api/admin/shareTip",
    getTipsDoneList: ApiBaseUrl + "/api/admin/completedTips",
    shareTipsAsPost: ApiBaseUrl + "/api/admin/shareTips",
    markTipAsDone: ApiBaseUrl + "/api/admin/tip",
    editTip: ApiBaseUrl + "/api/admin/editTip",
    scheduleTip: ApiBaseUrl + "/api/admin/scheduleTip",
    dismissTip: ApiBaseUrl + "/api/deleteMyTip",
    byIdGetNewsDetails: ApiBaseUrl + "/api/admin/news",
    adminCommentList: ApiBaseUrl + "/api/admin/comments",
    editEmployee: ApiBaseUrl + "/api/admin/editEmployee",
    adminReportComments: ApiBaseUrl + "/api/admin/reportedComments",
    adminDeleteComments: ApiBaseUrl + "/api/admin/deletedComments",
    adminUnReviewedComments: ApiBaseUrl + "/api/admin/unreviewedComents",
    editPost: ApiBaseUrl + "/api/admin/editnews",
    adminReplyComment: ApiBaseUrl + "/api/admin/replyComment",
    deletePost: ApiBaseUrl + "/api/admin/deletenews",
    getByIdEmployeeDetails: ApiBaseUrl + "/api/admin/empDetails",
    deleteEmployee: ApiBaseUrl + "/api/admin/empDelete",
    adminApproveComment: ApiBaseUrl + "/api/admin/approveComment",
    getApproveCommentList: ApiBaseUrl + "/api/admin/approveComment_list",
    deleteComment: ApiBaseUrl + "/api/admin/deleteComment",
    deleteMultiComments: ApiBaseUrl + "/api/admin/deleteComments",
    getempActivities: ApiBaseUrl + "/api/admin/empActivities",
    reportedComment: ApiBaseUrl + "/api/admin/reportedComment",
    getReportedComment: ApiBaseUrl + "/api/admin/reportedComment_list",
    getNewslikeList: ApiBaseUrl + "/api/admin/newsLike",
    getDashboardData: ApiBaseUrl + "/api/admin/dashboard",
    deleteSubComment: ApiBaseUrl + "/api/admin/deleteSubComment",
    unreviewComments: ApiBaseUrl + "/api/admin/unreviewComments",
    changePassword: ApiBaseUrl + "/api/changepassword",
    getParish: ApiBaseUrl + "/api/parish",
    addParish: ApiBaseUrl + "/api/admin/addparish",
    removeParish: ApiBaseUrl + "/api/admin/parishDelete",
    markAsTrending: ApiBaseUrl + "/api/trendingMark",
    draftPyayer: ApiBaseUrl + "/api/admin/draft",
    draftPrayerList: ApiBaseUrl + "/api/admin/draftPrayerList",
    draftTosharedNewsFeed: ApiBaseUrl + "/api/admin/draftTosharedNewsFeed",
    forgotPassword: ApiBaseUrl + "/api/forgotpassword",



};
